# Site settings
title: Satisfiable Code
email: aburnett88 at google mail dot com
description: > # this means to ignore newlines until "baseurl:"
  A website mostly discussing Haskell , SAT , NP hard problems , latex ,
  and anything else that I find generally interesting. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username: aburnett88

# Build settings
markdown: kramdown
